version = 0.1
[default.deploy.parameters]
stack_name = "course-api"
resolve_s3 = true
s3_prefix = "course-api"
region = "eu-central-1"
profile = "aws_cource"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentType=\"dev\""
image_repositories = []
